# Generated by Django 2.0.2 on 2018-03-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('activity_start_time', models.DateTimeField(help_text='The starting date and time for a jog')),
                ('distance', models.IntegerField(help_text='Distance in meters')),
                ('time', models.IntegerField(help_text='Time in minutes')),
            ],
        ),
    ]
