# Generated by Django 2.0.2 on 2018-03-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jog',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='jog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='jog',
            name='slug',
        ),
    ]
